### ISSUE TITLE
Update schema with 2020 geography

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#34]
Update schema files and text with 2020 geo info (to be used starting with R2020Q20.

**Comment by heathhayward** [comment]
Here are the new label files. Please use these for the 4.8.0 release. We need to do some research on the extent to which other schema changes are necessary (i.e. text changes and shapefiles).

[labels_4.8.0.zip](https://github.com/LEDApplications/lehd-schema/files/6224070/labels_4.8.0.zip)

**Comment by jodyhoonstarr** [comment]
Note to self: check the diff of the geo label files to see what it says about 2019 vs 2020 tiger/grf differences

**Comment by jodyhoonstarr** [comment]
Looks like the only change is in AK counties with the removal of `02261 Valdez-Cordova` and the addition of `02063 Chugach` and `02066 Copper River`.

**Comment by jodyhoonstarr** [comment]
The `label_geography.csv` also deleted the PSEO divisions. Looks like an accident to me - going to add them back and commit the changes.
```-Z,Unclassified,D
-1,New England Division,D
-2,Middle Atlantic Division,D
-3,East North Central Division,D
-4,West North Central Division,D
-5,South Atlantic Division,D
-6,East South Central Division,D
-7,West South Central Division,D
-8,Mountain Division,D
-9,Pacific Division,D
```

**Comment by srt1** [comment]
Will create a production ticket to update that. Thanks.

The county changes seem to make sense. And I think they had announced a while back that they were fixing the metro areas until after 2020, was it?
________________________________

**Comment by heathhayward** [comment]
ok that's great. I'll look into finding shapefiles that match these tabulation areas.

**Comment by jodyhoonstarr** [comment]
Just draw a line down the middle of 2019 valdez-cordova. It'll be fine.

**Comment by srt1** [comment]
BTW, on Jody's earlier comment, wasn't so much an accident about the Divisions, inasmuch as  it was never pulled into production in the first place. There's a ticket now for us to do it in the future - or at least to recognize that we haven't done it yet when this happens again.

Feel free to start additional production tickets with anything else that need fixing.
________________________________

**Comment by heathhayward** [comment]
Here are the text changes needed for the shapefile schema page:

1. https://ledapplications.github.io/lehd-schema/formats/V4.8.0/lehd_shapefiles.html#_sources should be changed to the following:

Files are derived from [TIGER/Line 2020 shapefiles](https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.2020.html) (except the "gb" and "gm" shapefile types, which are still sourced from [TIGER/Line 2019](https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.2019.html)):

- [tl_2020_us_state](https://www2.census.gov/geo/tiger/TIGER2020/STATE/) 

- [tl_2020_us_county](https://www2.census.gov/geo/tiger/TIGER2020/COUNTY/)

- [tl_2019_us_cbsa](https://www2.census.gov/geo/tiger/TIGER2019/CBSA/)

- [tl_2020_(ST)_place](https://www2.census.gov/geo/tiger/TIGER2020/PLACE/) (for creation of WIA/WIB shapefile)

- [tl_2020_(ST)_cousub](https://www2.census.gov/geo/tiger/TIGER2020/COUSUB/) (for creation of WIA/WIB shapefile)

2. On https://ledapplications.github.io/lehd-schema/formats/V4.8.0/lehd_shapefiles.html#_values, the label CSV files need to be replaced (i.e. https://ledapplications.github.io/lehd-schema/formats/V4.8.0/label_geography.csv) so they show the updated list of geography areas. But maybe those files have already been updated? I see "Chugach, AK" county in the above file so maybe this is already done.

3. Same thing with the new shapefiles - so that the links in https://ledapplications.github.io/lehd-schema/formats/V4.8.0/lehd_shapefiles.html#_common_files (and https://ledapplications.github.io/lehd-schema/formats/V4.8.0/lehd_shapefiles.html#_qwi_geographies) point to the new data. I'll add those files to this ticket soon.

4. Lastly, we can have https://ledapplications.github.io/lehd-schema/formats/V4.8.0/lehd_shapefiles.html#_changes_from_4_7_0 say:

- Underlying geovintage updated to reflect 2020 TIGER/Line geography (except for CBSAs - "gb" and "gm" features)

- Updated shapefiles based on TIGER/Line 2020 (except for CBSAs - "gb" and "gm" shapefile types)

**Comment by jodyhoonstarr** [comment]
Re 2 and 3 - those files are dynamically populated with the contents of the directory when the latest commit was made. You should be able to validate the csv files here on github but the new changes to the shapefile process means they won't work until we drop them into place on the webservers.

**Comment by heathhayward** [comment]
Two issues in https://ledapplications.github.io/lehd-schema/formats/V4.8.0/lehd_shapefiles.html#_sources, otherwise this looks good to go:

- The link to the 2020 shapefiles at the top isn't rendering correctly - it should look like the 2019 shapefile link in the parentheses.
- The 3rd bullet should read "tl_2019_us_cbsa" instead of "tl_2020_us_cbsa". The hyperlink destination is correct.

**Comment by heathhayward** [comment]
Also, want me to go ahead and transfer "lehd_shp_gc.zip", "lehd_shp_gs.zip" and "lehd_shp_gw.zip" from X:\geo\shp_export_04072021 to /data/rawdata/schema_repository/lehd-schema/formats/V4.8.0 on DEV? Or should I wait until we've pushed the updated V4.8.0 to DEV via [these instructions](https://uscensus.sharepoint.com/:w:/r/teams/ces/lehd/websystems/_layouts/15/Doc.aspx?sourcedoc=%7B7513AB10-AFC2-435A-83BB-F7C0CEC2DC19%7D&file=Schema%20Update%20instructions.docx&action=default&mobileredirect=true) so nothing gets overwritten?

Looking at the /data/rawdata/schema_repository/, should we delete "ticket1204_schema"? Seems like that was a Lars thing and you are using "lehd-schema" as the repository.

**Comment by jodyhoonstarr** [comment]
Hold up on the transfer. Need an updated version of ruby on dev so that we can build the schemadocs in house. I'll get you some updated instructions.

**Comment by jodyhoonstarr** [comment]
And yeah, we can remove any of those leftover redmine things like ticket1204_schema.

**Comment by jodyhoonstarr** [comment]
FYI: Shapefiles (and PDFs!) no longer live in this repo. They get generated once we go to create and deploy an official release. They were getting kinda big and don't work well within git.

**Comment by heathhayward** [comment]
In http://lehdweb.dev.ces.census.gov/data/schema/latest/lehd_shapefiles.html#_sources, the 3rd bullet should read "tl_2019_us_cbsa" instead of "tl_2020_us_cbsa". The hyperlink destination should go to the 2019 TIGER shapefile https://www2.census.gov/geo/tiger/TIGER2019/CBSA/.

We don't have to fix this right now, we can wait until next week when things are calmed down.

**Comment by jodyhoonstarr** [comment]
Forgot that the "fix" keyword will close an issue.

Right, because of the mixed vintages that should be 2019. It's fixed now if you want to push it out with 4.8.0. Essentially all you'd need to do is the 'git pull' and './process_latest.sh' script. From there you'd copy the lehd_shapefiles.html and lehd_shapefiles.pdf file into the schema directory on the website. Following the full set of steps will do the trick too if it's more clear.

**Comment by heathhayward** [comment]
Seems like this file http://lehdweb.dev.ces.census.gov/data/schema/V4.8.0/tmp2.csv is extra and should be removed? I'll delete it from DEV if you also delete it from GIT.

**Comment by heathhayward** [comment]
Thanks for making that change so quickly. I ran the full set of instructions and it looked good on DEV. I went ahead and pushed the schema out - you can see it at https://lehd.ces.census.gov/data/schema/V4.8.0/lehd_public_use_schema.html
