### ISSUE TITLE
Change institution length

### ISSUE THREAD

**Issue by andrewfoote** [LEDApplications/DEPRECATED-lehd-schema#6]
OPEID in past releases has been length 6, but we need to make it length 8 and have an updated OPEID list.

Things we need to do here:

- [x] Update the CSV that feeds into schema.
- [x] Change length of institution identifier.

**Comment by andrewfoote** [comment]
For point 1, sourcing is here: 

https://www2.ed.gov/offices/OSFAP/PEPS/dataextracts.html

**Comment by srt1** [comment]
Please update the text of schema section 6.13.2 to display the following link:

https://www2.ed.gov/offices/OSFAP/PEPS/dataextracts.html

**Comment by srt1** [comment]
Jody, please see previous comment about modifying text in 6.13.2. Thanks.

**Comment by jodyhoonstarr** [comment]
Link fixed in https://github.com/LEDApplications/lehd-schema/issues/18

**Comment by srt1** [comment]
Just a couple of final modifications (I think):


_XXX Cancel this one XXX_
* Add the following  parenthetical to the description. It should read (not italicized):

_... This list has been supplemented with records for regional groupings of institutions (may be used in future PSEO tabulations)._
_XXX END - annoying that strikethrough isn't a thing XXX_

* As in the other tables that are incomplete, can we add rows with ellipses before and after the selected institutions?
Since these are not consecutive records, we should technically have blank rows between each, but that is probably overkill. We should indicate that this is not the universe, though, with the top and bottom.

**Comment by srt1** [comment]
Sorry, cancel that first bit - we mention it in the "Institutional Levels" section. Just the ellipses lines, then.

**Comment by srt1** [comment]
BTW, @andrewfoote, I see you have a fancy checkbox thing up there - does one traditionally check those off before closing the ticket?

**Comment by srt1** [comment]
@jodyhoonstarr  - I see you weren't assigned; just in case, alerting you to the request to add lines with ellipses to the table in 6.13.2 (before and after the selected institutions)

**Comment by andrewfoote** [comment]
@srt1 You don't have to, but it helps me to keep track at the start of a ticket what exactly needs to happen (usually in non-production / research-y environments)

**Comment by jodyhoonstarr** [comment]
Adding the "..." to indicate that there are rows above or below in the table is something I'm trying to move away from. It may have been one of the original reasons why Lars used bash wrapped asciidoc rather than the vanilla language features. As this schema gets larger the shell scripts end up being brittle. Let me look around to see if there's something similar that's built into the original asciidoc language.

**Comment by srt1** [comment]
Sorry about that. I think it is useful to show that to indicate when we are presenting just a sample - particularly in this case, where we have specific institutions listed, and they are not the full list of institutions in the (next) release.  If you can think of a better way to present this and maintain it mechanically, ideas are most welcome.

I don't see it in the last one that was posted - is that because you need to rerun something?

**Comment by jodyhoonstarr** [comment]
It generally takes ~2-3mins for the new version to be built from when the commit arrives. If you don't see a change after that time then you may need to clear your browser cache (or open in another browser).

**Comment by jodyhoonstarr** [comment]
With the added caveat that if something breaks, that little icon that says "build passing" on the [main page](https://github.com/LEDApplications/lehd-schema) will turn red and say "build failed". If it breaks, then you'll be seeing the last successful version.

**Comment by srt1** [comment]
I still don't see the ellipses in the rows of 6.13.2 - did you add that?

**Comment by jodyhoonstarr** [comment]
No I didn't add that. I'm looking to see if it can be done without using bash.

**Comment by srt1** [comment]
OK, will leave it open for now.

As far as I am concerned, that is the last change I would like to see, if it isn't too terrible mechanically. I'm leaving #1 and #2 open pending Heath's signoff, but I don't think it will be controversial.

**Comment by srt1** [comment]
BTW, don't kill yourself to cludge this now - I know you are still working on reengineering the system. I do think the ability to provide display versions that are annotated to indicate incompleteness is a good thing, but there's probably a much cleaner way to do it globally. If this is not the best time to go after that issue, we can push it forward.

**Comment by jodyhoonstarr** [comment]
It wasn't actually that bad. I just had the syntax wrong. Future versions will need a comment or two about exactly what's being done but that's for another day.

**Comment by srt1** [comment]
looks good, thanks

**Comment by srt1** [comment]
Section 5.2.5

Identifier list needs to say Char(8) for OPEID

**Comment by srt1** [comment]
Jody, if this takes properly in 4.7.0, can you rebuild?

**Comment by jodyhoonstarr** [comment]
Will do
